config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|pl/ do
    root to: 'homepage#index'
    get '/news', to: 'news#index'
    get '/news/:id', to: 'news#show', as: 'news_item'
    get '/bio', to: 'bio#index'
    get '/concerts', to: 'concerts#index'
    get '/contact', to: 'contact#index'
    get '/gallery', to: 'gallery#index'
    get '/media', to: 'media#index'
    get '/projects', to: 'projects#index'
    get '/albums', to: 'albums#index'
  end

  get '/fetch_concerts/:year', to: 'concerts#fetch_concerts', as: 'fetch_concerts'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :project

  mount_uploader :cover, AlbumCoverUploader

  validates_presence_of :name, :year, :cover, :description, :english_description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  validates_presence_of :city, :date, :name, :venue
  scope :in_future_years, -> { where("date > ?", Date.new(Date.today.year + 1)) }
  scope :in_year, ->(year) { where(date: Date.new(year)..Date.new(year).end_of_year) }
  scope :recent, -> { order('date desc').limit(8) }
  scope :upcoming, -> { where('date > ?', Date.today).order('date asc').limit(8) }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/gallery_photo.rb
class GalleryPhoto < ApplicationRecord
  mount_uploader :picture, GalleryPhotoUploader
end

app/models/homepage_photo.rb
class HomepagePhoto < ApplicationRecord
  mount_uploader :picture, HomepagePhotoUploader

  before_save :set_active

  private

  def set_active
    HomepagePhoto.where.not(id: id).update_all(active: false)
  end
end

app/models/media_page.rb
class MediaPage < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  validates_presence_of :polish_title, :polish_content
  has_rich_text :polish_content
  has_rich_text :english_content
end

app/models/project.rb
class Project < ApplicationRecord
  default_scope { order(order: :asc) }
  attr_accessor :photos
  serialize :photos
  validates_presence_of :name, :description, :english_description

  has_many :albums
  has_many :project_photos
end

app/models/project_photo.rb
class ProjectPhoto < ApplicationRecord
  belongs_to :project
  mount_uploader :picture, ProjectPhotoUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  expose_decorated(:albums, collection: true, decorator: AlbumsDecorator) do
    Album.order(order: :asc)
  end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  expose(:photos) { GalleryPhoto.all }
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  expose_decorated(:concerts, collection: true, decorator: ConcertDecorator) { upcoming_concerts.limit(7) }
  expose_decorated(:news, collection: true, decorator: NewsDecorator) { News.all }
  expose(:homepage_picture) { HomepagePhoto.find_by(active: true) || HomepagePhoto.last }

  private

  def upcoming_concerts
    Concert.upcoming || Concert.recent
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  expose_decorated(:news_items, collection: true, decorator: NewsDecorator) { News.all }
  expose_decorated(:news)
  before_action :find_news, only: :show

  private

  def find_news
    @news = News.find(params[:id]).decorate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def concert_years
    Concert.all.pluck(:date).map(&:year).uniq
  end

  def current_year
    Date.today.year
  end

  def future_concerts_years
    Concert.in_future_years.pluck(:date).map(&:year).uniq
  end

  def past_concerts_years
    Concert.where("date < ?", Date.today.beginning_of_year).pluck(:date).map(&:year).sort.uniq
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_photo_style(photo)
    "background-image: url(#{photo.picture.url(:medium)})"
  end
end

app/views/homepage/_news.html.haml
.homepage__news-wrapper
  - news.each do |news_item|
    = render 'news_item', news_item: news_item

app/views/homepage/_news_item.html.haml
.homepage__news-item-container
  .homepage__news-item-title-container
    = link_to news_item_path(news_item), class: 'homepage__news-item-title-link' do
      %h1.homepage__news-item-title= news_item.title
  .homepage__news-item-content-container
    %p.homepage__news-item-content= (sanitize news_item.content.body.to_plain_text.truncate(400), tags: %w( iframe ), attributes: %w(src source width height))
  = link_to t('news.read_more'), news_item_path(news_item), class: 'homepage__news-item-read-more'

app/views/homepage/_picture.html.haml
.homepage__picture{ style: "background-image: url('#{homepage_picture.picture.url}')" }
  .homepage__picture-social-icons-container
    = link_to 'http://instagram.com/marcelbalinski', target: '_blank' do
      .homepage__picture-social-icon.homepage__picture-social-icon--instagram
    = link_to 'https://www.facebook.com/marcel.balinski', target: '_blank' do
      .homepage__picture-social-icon.homepage__picture-social-icon--facebook
  .homepage__mobile-music-socials
    = link_to 'spotify:artist:7m6aeZvZbUT5Gt2kBZ0bNt' do
      .homepage__mobile-music-link.homepage__mobile-music-link--spotify
    = link_to 'https://soundcloud.com/user-32343881-493664261', target: '_blank' do
      .homepage__mobile-music-link.homepage__mobile-music-link--soundcloud
    = link_to 'https://www.youtube.com/watch?v=KQuEJj4XDpk', target: '_blank' do
      .homepage__mobile-music-link.homepage__mobile-music-link--youtube

app/views/homepage/_upcoming_concerts.html.haml
.homepage__concerts-wrapper
  - concerts.each do |concert|
    = render 'concert', concert: concert
  = button_tag t('homepage.all_concerts'), type: 'button', class: "button button__desktop-button homepage__button button--more-concerts", onclick: "location.href = '#{concerts_path}'"
.homepage__social-icons
  = link_to 'spotify:artist:7m6aeZvZbUT5Gt2kBZ0bNt' do
    .homepage__mobile-music-link.homepage__mobile-music-link--spotify
  = link_to 'https://soundcloud.com/user-32343881-493664261', target: '_blank' do
    .homepage__mobile-music-link.homepage__mobile-music-link--soundcloud
  = link_to 'https://www.youtube.com/watch?v=KQuEJj4XDpk', target: '_blank' do
    .homepage__mobile-music-link.homepage__mobile-music-link--youtube

app/views/homepage/index.html.haml
= render 'picture'
= render 'news'