config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|pl/ do
    root to: 'homepage#index'
    get '/news', to: 'news#index'
    get '/news/:id', to: 'news#show', as: 'news_item'
    get '/bio', to: 'bio#index'
    get '/concerts', to: 'concerts#index'
    get '/contact', to: 'contact#index'
    get '/gallery', to: 'gallery#index'
    get '/media', to: 'media#index'
    get '/projects', to: 'projects#index'
    get '/albums', to: 'albums#index'
  end

  get '/fetch_concerts/:year', to: 'concerts#fetch_concerts', as: 'fetch_concerts'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :project

  mount_uploader :cover, AlbumCoverUploader

  validates_presence_of :name, :year, :cover, :description, :english_description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  validates_presence_of :city, :date, :name, :venue
  scope :in_future_years, -> { where("date > ?", Date.new(Date.today.year + 1)) }
  scope :in_year, ->(year) { where(date: Date.new(year)..Date.new(year).end_of_year) }
  scope :recent, -> { order('date desc').limit(8) }
  scope :upcoming, -> { where('date > ?', Date.today).order('date asc').limit(8) }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/gallery_photo.rb
class GalleryPhoto < ApplicationRecord
  mount_uploader :picture, GalleryPhotoUploader
end

app/models/homepage_photo.rb
class HomepagePhoto < ApplicationRecord
  mount_uploader :picture, HomepagePhotoUploader

  before_save :set_active

  private

  def set_active
    HomepagePhoto.where.not(id: id).update_all(active: false)
  end
end

app/models/media_page.rb
class MediaPage < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  validates_presence_of :polish_title, :polish_content
  has_rich_text :polish_content
  has_rich_text :english_content
end

app/models/project.rb
class Project < ApplicationRecord
  default_scope { order(order: :asc) }
  attr_accessor :photos
  serialize :photos
  validates_presence_of :name, :description, :english_description

  has_many :albums
  has_many :project_photos
end

app/models/project_photo.rb
class ProjectPhoto < ApplicationRecord
  belongs_to :project
  mount_uploader :picture, ProjectPhotoUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  expose_decorated(:albums, collection: true, decorator: AlbumsDecorator) do
    Album.order(order: :asc)
  end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  expose(:photos) { GalleryPhoto.all }
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  expose_decorated(:news_items, collection: true, decorator: NewsDecorator) { News.all }
  expose_decorated(:news)
  before_action :find_news, only: :show

  private

  def find_news
    @news = News.find(params[:id]).decorate
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def concert_years
    Concert.all.pluck(:date).map(&:year).uniq
  end

  def current_year
    Date.today.year
  end

  def future_concerts_years
    Concert.in_future_years.pluck(:date).map(&:year).uniq
  end

  def past_concerts_years
    Concert.where("date < ?", Date.today.beginning_of_year).pluck(:date).map(&:year).sort.uniq
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_photo_style(photo)
    "background-image: url(#{photo.picture.url(:medium)})"
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_header.html.haml
.header
  .header__language-switcher
    - if current_page?(locale: :pl) || I18n.locale == :pl
      .header__language-container.header__language-container--en
        = link_to(options = { locale: "en" }) do
          %span.header__language.mobile-nav__language--en EN
    - elsif current_page?(locale: :en) || I18n.locale == :en
      .header__language-container.header__language-container--pl
        = link_to(options = { locale: "pl" }) do
          %span.header__language.mobile-nav__language--pl PL
  = link_to root_path do
    %h1.header-title= t('header.marcel')
    %h2.header-subtitle
      = t('header.pianist')
      |
      = t('header.composer')

app/views/shared/_mobile_nav.html.haml
.mobile-nav
  .mobile-nav__burger-wrapper
    .mobile-nav__hamburger-menu
  .mobile-nav__language-picker
    - if current_page?(locale: :pl) || I18n.locale == :pl
      .mobile-nav__language-container.mobile-nav__language-container--en
        = link_to(options = { locale: "en" }) do
          %span.mobile-nav__language.mobile-nav__language--en EN
    - elsif current_page?(locale: :en)
      .mobile-nav__language-container.mobile-nav__language-container--pl
        = link_to(options = { locale: "pl" }) do
          %span.mobile-nav__language.mobile-nav__language--pl PL
.mobile-nav__slider
  %ul.mobile-nav__menu-items
    - %w(homepage bio concerts projects albums media contact).each do |page|
      %li.mobile-nav__menu-item{ class: ("active" if controller_name == page) }
        = link_to controller: page, action: "index" do
          .mobile-nav__menu-item-container
            %span= t("navigation.#{page}")

app/views/shared/_nav.html.haml
.nav.hidden-xs.hidden-sm.d-flex.justify-content-end
  .ul.nav__menu-items
    %li.nav__menu-item{ class: ("active" if controller_name == 'home') }
      = link_to controller: 'homepage', action: "index" do
        .nav__menu-item-container
          %span= t("navigation.home")
    %li.nav__menu-item{ class: ("active" if controller_name == 'bio') }
      = link_to controller: 'bio', action: "index" do
        .nav__menu-item-container
          %span= t("navigation.bio")
    %li.nav__menu-item{ class: ("active" if controller_name == 'concerts') }
      = link_to controller: 'concerts', action: "index" do
        .nav__menu-item-container
          %span= t("navigation.concerts")
    %li.nav__menu-item{ class: [("active" if controller_name == 'projects'), "dropdown"] }
      = link_to controller: 'projects', action: "index" do
        .nav__menu-item-container
          %span.nav__menu-link= t("navigation.projects")
      .dropdown-content
        - @navbar_projects.each do |project|
          = link_to project.name, projects_path(anchor: project.name.parameterize.underscore), class: "nav__dropdown-project-link"
    %li.nav__menu-item{ class: ("active" if controller_name == 'albums') }
      = link_to controller: 'albums', action: "index" do
        .nav__menu-item-container
          %span= t("navigation.albums")
    %li.nav__menu-item{ class: ("active" if controller_name == "media") }
      = link_to controller: "media", action: "index" do
        .nav__menu-item-container
          %span= t("navigation.media")
    %li.nav__menu-item{ class: ("active" if controller_name == 'contact') }
      = link_to controller: 'contact', action: "index" do
        .nav__menu-item-container
          %span= t("navigation.contact")