config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|pl/ do
    root to: 'homepage#index'
    get '/news', to: 'news#index'
    get '/news/:id', to: 'news#show', as: 'news_item'
    get '/bio', to: 'bio#index'
    get '/concerts', to: 'concerts#index'
    get '/contact', to: 'contact#index'
    get '/gallery', to: 'gallery#index'
    get '/media', to: 'media#index'
    get '/projects', to: 'projects#index'
    get '/albums', to: 'albums#index'
  end

  get '/fetch_concerts/:year', to: 'concerts#fetch_concerts', as: 'fetch_concerts'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :project

  mount_uploader :cover, AlbumCoverUploader

  validates_presence_of :name, :year, :cover, :description, :english_description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concert.rb
class Concert < ApplicationRecord
  validates_presence_of :city, :date, :name, :venue
  scope :in_future_years, -> { where("date > ?", Date.new(Date.today.year + 1)) }
  scope :in_year, ->(year) { where(date: Date.new(year)..Date.new(year).end_of_year) }
  scope :recent, -> { order('date desc').limit(8) }
  scope :upcoming, -> { where('date > ?', Date.today).order('date asc').limit(8) }
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/gallery_photo.rb
class GalleryPhoto < ApplicationRecord
  mount_uploader :picture, GalleryPhotoUploader
end

app/models/homepage_photo.rb
class HomepagePhoto < ApplicationRecord
  mount_uploader :picture, HomepagePhotoUploader

  before_save :set_active

  private

  def set_active
    HomepagePhoto.where.not(id: id).update_all(active: false)
  end
end

app/models/media_page.rb
class MediaPage < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  validates_presence_of :polish_title, :polish_content
  has_rich_text :polish_content
  has_rich_text :english_content
end

app/models/project.rb
class Project < ApplicationRecord
  default_scope { order(order: :asc) }
  attr_accessor :photos
  serialize :photos
  validates_presence_of :name, :description, :english_description

  has_many :albums
  has_many :project_photos
end

app/models/project_photo.rb
class ProjectPhoto < ApplicationRecord
  belongs_to :project
  mount_uploader :picture, ProjectPhotoUploader
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  expose_decorated(:albums, collection: true, decorator: AlbumsDecorator) do
    Album.order(order: :asc)
  end
end

app/controllers/bio_controller.rb
class BioController < ApplicationController

end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  expose_decorated(:concerts, collection: true, decorator: ConcertDecorator) do
    Concert.where(date: Date.today.beginning_of_year..Date.today.end_of_year).order('date desc')
  end
  expose(:years) do
    Concert.pluck(:date).map(&:year).uniq.reject { |year| year == Date.today.year }
  end

  def fetch_concerts
    year = params[:year].present? ? params[:year].to_i : Date.today.year
    @selected_concerts = Concert.in_year(year).decorate

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  expose(:photos) { GalleryPhoto.all }
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  expose_decorated(:concerts, collection: true, decorator: ConcertDecorator) { upcoming_concerts.limit(7) }
  expose_decorated(:news, collection: true, decorator: NewsDecorator) { News.all }
  expose(:homepage_picture) { HomepagePhoto.find_by(active: true) || HomepagePhoto.last }

  private

  def upcoming_concerts
    Concert.upcoming || Concert.recent
  end
end

app/controllers/media_controller.rb
class MediaController < ApplicationController
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  expose_decorated(:news_items, collection: true, decorator: NewsDecorator) { News.all }
  expose_decorated(:news)
  before_action :find_news, only: :show

  private

  def find_news
    @news = News.find(params[:id]).decorate
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  expose_decorated(:projects, collection: true, decorator: ProjectsDecorator) { Project.all }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
  def concert_years
    Concert.all.pluck(:date).map(&:year).uniq
  end

  def current_year
    Date.today.year
  end

  def future_concerts_years
    Concert.in_future_years.pluck(:date).map(&:year).uniq
  end

  def past_concerts_years
    Concert.where("date < ?", Date.today.beginning_of_year).pluck(:date).map(&:year).sort.uniq
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_photo_style(photo)
    "background-image: url(#{photo.picture.url(:medium)})"
  end
end

app/views/concerts/_concert.html.haml
.concerts__concert
  .concerts__concert-date-container
    .span.concerts__concert-date.concerts__concert-date--day= concert.day
    %hr.concerts__concert-date-separator
    .span.concerts__concert-date.concerts__concert-date--year= concert.year
  .concerts__concert-details-container
    .concerts__concert-details
      .concerts__concert-name-container
        %h2.concerts__concert-name= concert.name
        - if concert.link.present?
          = link_to concert.link, class: "concerts__concert-link-container concerts__concert-link-container--mobile", target: "_blank" do
            .concerts__concert-link
      .concerts__concert-location-details
        %span.concerts__concert-city
          = concert.location
    .concerts__concert-extras
      - if concert.festival_name.present?
        %span.concerts__concert-festival= concert.festival_name
      - if concert.details.present?
        %span.concerts__concert-description= concert.details
    - if concert.link.present?
      = link_to concert.link, class: "concerts__concert-link-container concerts__concert-link-container--desktop", target: "_blank" do
        .concerts__concert-link

app/views/concerts/_concerts.html.haml
%h1= year
- concerts.each do |concert|
  = render 'concert', concert: concert

app/views/concerts/fetch_concerts.js.erb
$('.concerts__concerts-list-wrapper').html("<%= j render 'concerts', concerts: @selected_concerts %>")

app/views/concerts/index.html.haml
.concerts__years-slider-mobile-container.col-xs-12
  - past_concerts_years.each do |year|
    = link_to year, fetch_concerts_path(year: year), class: "concerts__year-link", remote: true
  = link_to current_year, fetch_concerts_path(year: current_year), class: "concerts__year-link active", remote: true
  - future_concerts_years.each do |year|
    = link_to year, fetch_concerts_path(year: year), class: "concerts__year-link", remote: true
-# .concerts__years-slider-container.col-md-3.col-md-offset-1
-#   - future_concerts_years.each do |year|
-#     = link_to year, fetch_concerts_path(year: year), class: "concerts__year-link", remote: true
-#   = link_to current_year, fetch_concerts_path(year: current_year), class: "concerts__year-link active", remote: true
-#   - past_concerts_years.reverse.each do |year|
-#     = link_to year, fetch_concerts_path(year: year), class: "concerts__year-link", remote: true
.concerts__concerts-list-wrapper.col-xs-12.col-md-12
  = render 'concerts', concerts: concerts, year: Date.today.year
  - years.each do |year|
    = render 'concerts', concerts: Concert.all.order('date desc').decorate.select { |c| c.date.year == year }, year: year

app/views/projects/_album.html.haml
.projects__album-container.col-xs-12
  - if album.cover.url.present?
    .projects__album-cover-container.col-md-4.col-md-offset-1
      = image_tag album.cover.url, class: "projects__album-cover"
  .projects__album-details.col-md-7
    .projects__album-details-container.col-md-12.col-xs-12
      %h2.projects__album-title= album.name
      %h4.projects__album-year= "(#{album.year})"
      .projects__album-description-container
        - if current_page?(locale: :pl) || I18n.locale == :pl
          %span.projects__album-description= simple_format(album.description)
        - elsif current_page?(locale: :en)
          %span.projects__album-description= simple_format(album.english_description)
      - if album.buy_cd_link.present?
        = button_tag t('projects.buy_album'), type: 'button', class: "button button__buy-album", onclick: "location.href = '#{album.buy_cd_link}'"
    - if project.albums.size > 1
      %hr.projects__albums-separator.visible-xs.visible-sm/

app/views/projects/_project.html.haml
.projects__project-wrapper.col-md-12
  .projects__project-header-container.col-xs-12.col-md-6
    %h1.projects__project-header= project.name
  - if project.project_photos.any?
    .projects__project-photos-container.col-xs-12.col-md-4
      - project.project_photos.each do |photo|
        .projects__photo-container{ style: project_photo_style(photo) }
  .projects__project-container.col-xs-12{ class: (project.project_photos.any? ? "col-md-7" : "col-md-12") }
    .projects__project-header-container-desktop.hidden-xs.hidden-sm
      %h1.projects__project-header.hidden-xs.hidden-sm{ id: "#{project.name.parameterize.underscore}" }= project.name
    .projects__project-description-container
      - if current_page?(locale: :pl) || I18n.locale == :pl
        %p.projects__project-description= project.description
      - elsif current_page?(locale: :en)
        %p.projects__project-description= project.english_description
      = render 'project_socials', project: project

app/views/projects/_project_socials.html.haml
.projects__project-social-icons-container.col-xs-8.col-xs-offset-2.col-md-6.col-md-offset-0
  - if project.spotify_link.present?
    = link_to project.spotify_link, class: "projects__social-icon-link" do
      .projects__social-icon.projects__social-icon--spotify
  - if project.instagram_link.present?
    = link_to project.instagram_link, class: "projects__social-icon-link" do
      .projects__social-icon.projects__social-icon--instagram
  - if project.youtube_link.present?
    = link_to project.youtube_link, class: "projects__social-icon-link" do
      .projects__social-icon.projects__social-icon--youtube
  - if project.fb_link.present?
    = link_to project.fb_link, class: "projects__social-icon-link" do
      .projects__social-icon.projects__social-icon--facebook

app/views/projects/index.html.haml
.projects__projects-wrapper.col-xs-12
  - projects.each do |project|
    .projects__row
      = render "project", project: project